"""initial schema

Revision ID: 32ce1feafe38
Revises: 
Create Date: 2026-05-27 18:59:55.355069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '32ce1feafe38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('battery_pct', sa.SmallInteger(), nullable=False),
    sa.Column('speed_mps', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_codes', sa.JSON(), nullable=False),
    sa.Column('zone_entered', sa.String(length=50), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telemetry_events_vehicle_timestamp', 'telemetry_events', ['vehicle_id', 'timestamp'], unique=False)
    op.create_table('vehicle_states',
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('battery_pct', sa.SmallInteger(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('zone_counts',
    sa.Column('zone_id', sa.String(length=50), nullable=False),
    sa.Column('entry_count', sa.BigInteger(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('telemetry_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['telemetry_event_id'], ['telemetry_events.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle_states.vehicle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomalies_vehicle_detected_at', 'anomalies', ['vehicle_id', 'detected_at'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle_states.vehicle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_vehicle_id'), 'missions', ['vehicle_id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle_states.vehicle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_mission_id'), 'maintenance_records', ['mission_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_vehicle_id'), 'maintenance_records', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_records_vehicle_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_mission_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_missions_vehicle_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index('ix_anomalies_vehicle_detected_at', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_table('zone_counts')
    op.drop_table('vehicle_states')
    op.drop_index('ix_telemetry_events_vehicle_timestamp', table_name='telemetry_events')
    op.drop_table('telemetry_events')
    # ### end Alembic commands ###
